name: oss-vizier
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - pip:
      - google-vizier[jax]==0.1.20
      - jax>=0.4.34,<0.5
      - jaxlib>=0.4.34,<0.5
      - jaxopt>=0.8.3
      - flax>=0.10.0
      - optax>=0.2.3
      - chex>=0.1.87
      - tfp-nightly[jax]
      - equinox==0.11.7
      - jaxtyping>=0.2.34
      - typeguard<=2.13.3
      - sqlalchemy>=1.4
